### ISSUE TITLE
Full Export not exporting all scenes

### ISSUE THREAD

**Issue by CodeHelix** [fehaar/FFWD-Templates#7]
When doing a Full Export it only looks for the Logo scene and ignores all other scenes so have to export open scene in order to export a different scene as export all scenes just sits at the loading pop up screen for exporting all scenes.

**Comment by fehaar** [comment]
By default it does not know what scenes to export. And you do not want it to export every scene in the project. To add a scene to the list to export, open the Configuration dialog and put the scene in the list of scenes. Note that you can divide your scenes into groups so you only export some groups (exporting can take a lot of time on large projects).

**Comment by CodeHelix** [comment]
Ah ok. That makes sense. Thanks for clearing that up for me.

**Comment by fehaar** [comment]
It will get added to the docs at some point. I have created an issue for it - that is a start.

**Comment by cauerego** [comment]
Right now the config already comes with the scene, right? So I suppose it won't get added to the docs anymore. At least not in the Getting Started's template section.

**Comment by fehaar** [comment]
The config contains the first scenen, yes. But if you add additional scenes, they should be added manually.
